### PR TITLE
Initial UltraPlus 5k support

### PR DESCRIPTION
**Pull request by daveshah1**
This is early but somewhat working support for the ice40-up5k device. At the moment it has the following known limitations:

- Some new IO config bits are not being set correctly. The consequences of this, if any, aren't known, but it doesn't seem to affect basic IO functionality.

- The PLL hasn't been added yet

- No new UltraPlus features (DSP, SPRAM, I²C/SPI, etc) are supported yet

### CODE REVIEW

**Comment by daveshah1** [comment]
Typically find this in testing just after submitting the pull request, but it looks like most non-trivial designs will fail because 5k_glb_netwk_ bits are not being added to the database. I will investigate and update.

**Comment by daveshah1** [comment]
Hopefully the ColBufCtrls and global networks are set correctly now. Next step will be to do some testing to determine whether there is any purpose to the new IO configuration bits.

**Comment by cliffordwolf** [comment]
A minor nitpick: The ColBufCtrl bits for the 5k and the 8k seem to be identical. There is probably an argument to be had to simply reuse the `8k_glb_netwk_*` labels. (I'm not 100% sure what's the best approach here myself.)

But either way we should imo avoid adding 5k-only labels to an 8k-only section of iceboxdb (and vice versa). From your iceboxdb file:

```
database_ramb_8k_txt = """
B9[7]   ColBufCtrl  5k_glb_netwk_0
B8[7]   ColBufCtrl  5k_glb_netwk_1
B11[7]  ColBufCtrl  5k_glb_netwk_2
B10[7]  ColBufCtrl  5k_glb_netwk_3
B13[7]  ColBufCtrl  5k_glb_netwk_4
B12[7]  ColBufCtrl  5k_glb_netwk_5
B15[7]  ColBufCtrl  5k_glb_netwk_6
B14[7]  ColBufCtrl  5k_glb_netwk_7
B9[7]   ColBufCtrl  8k_glb_netwk_0
B8[7]   ColBufCtrl  8k_glb_netwk_1
B11[7]  ColBufCtrl  8k_glb_netwk_2
B10[7]  ColBufCtrl  8k_glb_netwk_3
B13[7]  ColBufCtrl  8k_glb_netwk_4
B12[7]  ColBufCtrl  8k_glb_netwk_5
B15[7]  ColBufCtrl  8k_glb_netwk_6
B14[7]  ColBufCtrl  8k_glb_netwk_7
```

**Comment by daveshah1** [comment]
Thanks for pointing that out! I'll have a look at a better solution, they are the same as far as I know so I agree reusing the labels is the best way forward.

**Comment by daveshah1** [comment]
I have fixed the above issue by sharing glb_netwk data between 5k and 8k parts, indeed they are identical in that regard.

It does seem like the mystery IO bits have some kind of purpose, although I still haven't worked out exactly what that purpose is. Setting the padeb_test bits to 1 on an output pin (the official tools set them to 1 unless a pin is used as an output) causes it to no longer function properly, instead it is stuck high - but not driven as hard as a normal high output. Why the padeb_test bits are set for an input is still unknown, input leakage current doesn't change but I haven't measured other parameters.

I think therefore it is a good idea to use them properly in the same way as the official tools do, as the fact they have some effect means it is clear they are not just dummy bits or leftovers from testing or prototype silicon.

**Comment by mirecta** [comment]
hi 
and internal osc now working ?
if yes , can u post some example ?
will u work on buildin IPs as SPI IIC etc ?
thanks for reply , your wok makes me happy

**Comment by daveshah1** [comment]
Hi

Unfortunately this is still very experimental - global buffers aren't even working reliably yet. None of the ultraplus specific features - oscillator, IP, DSP etc - have been implemented yet either but will be once the basic features are working.

**Comment by mirecta** [comment]
i understand 
its a good idea to create issue or something here, for watching progress , working features , problems etc about up5k,  i mean 
because first issue is closed and this pull request too.

**Comment by daveshah1** [comment]
I'll create a new pull request in a couple of days time, I've now hopefully solved most of the issues and done some more testing so soon it should be at the standard ice40 level of functionality. Then I plan to start working on the new UltraPlus features, first adding support the IPConnect and DSP tile types (without any special functionality at first) to icebox and arachne.

**Pull request merged**
