### PR TITLE
Squelch some more trailing whitespace

### PR DESCRIPTION
**Pull request by rlutz**
This commit completes the work started in b3d35cc.

Commit b3d35cc removed trailing whitespace at the end of a line, but it missed most trailing whitespace at the end of a file. This commit removes this whitespace, too.

### CODE REVIEW

**Comment by cliffordwolf** [comment]
What is the motivation for this? I usually like having an empty line at the end of the file. That's why you find that in so many files.

**Comment by rlutz** [comment]
I haven't seen such a style yet, but if it's your preference, then these newline characters should obviously stay.

May I ask what your motivation is for having them?

**Comment by cliffordwolf** [comment]
> May I ask what your motivation is for having them?

First let me be clear: It's not a strict coding style and I would be similarly reluctant to merge a patch that adds an extra newline to the end of all files that do not yet have them..

I guess the reason why I have them is that historically some editors display a trailing newline at the end of the file as an extra line (i.e. newline as line separator), whereas other editors assume that each line is terminated by a newline and thus nothing extra is displayed.

I assume we can all agree that the last line in a file should be terminated by a newline. And that no newline at all is worse than two newline characters at the end of the file.

I used to work with editors that display this final newline as extra line (decades ago). Vim (my current editor) doesn't do that, but I'm still uneasy if I don't see a blank line at the end of the file in my editor.

> if it's your preference, then these newline characters should obviously stay.

Closing this PR. :)

**Comment by rlutz** [comment]
> historically some editors display a trailing newline at the end of the file as an extra line (i.e. newline as line separator), whereas other editors assume that each line is terminated by a newline and thus nothing extra is displayed.

Most editors treat text files as a series of characters, one of which is the newline character. You have a text cursor which indicates where characters typed should be inserted. It can be placed in front of or after any character, including in front of the first or after the last character. If it couldn't, you wouldn't be able to insert characters at the end of the file.

Therefore, it makes total sense for such a text editor to allow placing the cursor at the beginning of the line immediately following the last line.

Vim, on the other hand, uses two complementary concepts in normal mode and insert mode. In normal mode, you select a *character*. A file is treated as a series of lines which is each made up of a series of characters. With the exception of an empty line, you can only place the cursor on an existing character; this character is operated on by the following command. In insert mode, a line is treated pretty much the same as it is in other editors. Depending on the way you use Vim, this may be indicated by a character-wide rectangle cursor vs. a thin vertical cursor.

Therefore, whether an empty line appears to be at the bottom of the file is not so much an editor idiosyncrasy as a logical consequence of the conceptual representation of a file. In Vim, you have a series of lines; if there's no empty line at the bottom of a file, then everything is right. In many other editors, you have a series of characters; if the last character is a newline, then again, everything is right.

**Comment by cliffordwolf** [comment]
(1) I do really know how editors work. But thanks anyways. </sarcasm>

(2) Most editors do not allow you to create nonempty files that do not end in a newline character. (Try it!) If your simplistic characterization of "most editors" were true then this would be possible.

(3) You do realize that dragging on this discussion cuts into the time I have left to do other things, like reviewing your other patches? @martinda

**Pull request closed without merging**
