### PR TITLE
Reduce icebox build time

### PR DESCRIPTION
**Pull request by mbuesch**
These changes reduce the icebox build time by using LRU caches for often called functions.
The over all (single core) build time is reduced by approximately 16%.
The resulting chipdb*.txt files do not change.

### CODE REVIEW

**Comment by cliffordwolf** [comment]
Oh, this is evil. :) @daveshah1 what do you think?

**Comment by mbuesch** [comment]
Yes, I fully understand, that this is kind of evil. :)

However I think the first part for tile_has_net is pretty straightforward and simple. A.k.a. not so evil. It's actually what lru_cache is meant to be used for. That part alone gives us about 50% of the performance gain.

The second part is a bit hacky due to the monkey patching.
However as far as we always get the same regex match for the same tuple of regex pattern and regex input, I think it's pretty safe. As far as I can see, that's always the case. One example where this would not be the case is e.g. if a callback is used and that callback has state.

The whole re monkey patching can be switched off for debugging, by turning off the if True, if somebody suspects some breakage.

It could be made a bit non-hackish-ier by changing all calls of all re functions in the project explicitly to a cached function call. However that's quite a big change and I personally don't think it's that much better.
Monkey patching is a quite common technique in Python.

**Comment by cliffordwolf** [comment]
> One example where this would not be the case is e.g. if a callback is used and that callback has state.

What about using something like the following instead, and changing the users to use `re_match_cached` instead of `re.match`? This way it would be more obvious to avoid `re_match_cached` in the cases where there could be a problem.

```
if True:
    @functools.lru_cache(maxsize=re_cache_sizes)
￼    def re_match_cached(*args):
￼        return re.match(*args)
else:
    re_match_cached = re.match
```

I think that would be much cleaner than monkey patching `re.match`, and would yield the same result.

**Comment by mbuesch** [comment]
Yes, I'm Ok with that.
It would be a huge patch, but that's Ok to me.
It would also mean that we don't sneak cached re to possible other users of re in the stdlib or somewhere else. Which is a good thing.

So if you agree, I'll change the pull request to implement that. As two separate commits: First introduce the cached wrappers and then change all users.

**Comment by cliffordwolf** [comment]
> So if you agree, I'll change the pull request to implement that. As two separate commits: First introduce the cached wrappers and then change all users.

SGTM :+1:

**Comment by mbuesch** [comment]
done

**Pull request merged**
